name: ai_prompt_evaluator
description: Example of vader_console.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  vader_console: 1.0.0-dev.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
